//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioscoConsulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AN_COMEDOR_USUARIO
    {
        public string USUARIO_COMEDOR { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string NUM_EMP { get; set; }
        public string NOMBRE { get; set; }
        public string AP_PATER { get; set; }
        public string AP_MATER { get; set; }
        public string CCOSTO { get; set; }
        public string PUESTO { get; set; }
        public string F_ALTA { get; set; }
        public string F_BAJA { get; set; }
        public string F_SUSPENCION { get; set; }
        public string CIA { get; set; }
        public string TIPO_NOM { get; set; }
        public string SIN_USO1 { get; set; }
        public string SIN_USO2 { get; set; }
        public string SN_USO3 { get; set; }
    }
}
