//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioscoConsulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AN_EMP
    {
        public string NUM_EMP { get; set; }
        public string NOMP_EMP { get; set; }
        public string AP_PATER { get; set; }
        public string AP_MATER { get; set; }
        public string TITULO { get; set; }
        public string SEXO { get; set; }
        public string F_NAC { get; set; }
        public string SIN_USO7 { get; set; }
        public string SIN_USO8 { get; set; }
        public string SIN_USO9 { get; set; }
        public string NUM_SOLIC { get; set; }
        public string RFC { get; set; }
        public string AJUSTE_ANUAL { get; set; }
        public string CRED_SALARIO { get; set; }
        public string F_ALTA { get; set; }
        public string F_INGRESO { get; set; }
        public string F_PLANTA { get; set; }
        public string F_BAJA { get; set; }
        public string F_BAJA_RESP { get; set; }
        public string F_BAJA_IMSS { get; set; }
        public string SIN_USO20 { get; set; }
        public string TURNO { get; set; }
        public string CLV_TARJ { get; set; }
        public string CCOSTO { get; set; }
        public string EST_ORG { get; set; }
        public string PLAZA { get; set; }
        public string PUESTO { get; set; }
        public string CATEGORIA { get; set; }
        public string CONTRATO { get; set; }
        public string TIPO_NOM { get; set; }
        public string TIPO_EMP { get; set; }
        public string F_DIST_PAGO { get; set; }
        public string TIPO_PAGO { get; set; }
        public string BCO_DEP { get; set; }
        public string CTA_BAN { get; set; }
        public string SUCURSAL { get; set; }
        public string RECINTO { get; set; }
        public string UBICA_FIS { get; set; }
        public string ZONA_EC { get; set; }
        public string GUIA_POSTAL { get; set; }
        public string SIN_USO40 { get; set; }
        public string IMSS { get; set; }
        public string NO_REG_PAT_IMSS { get; set; }
        public string TIPO_COT_IMSS { get; set; }
        public string CURP { get; set; }
        public string SIN_USO45 { get; set; }
        public string SIN_USO46 { get; set; }
        public string SIN_USO47 { get; set; }
        public string SIN_USO48 { get; set; }
        public string SIN_USO49 { get; set; }
        public string SIN_USO50 { get; set; }
        public string TABULADOR { get; set; }
        public Nullable<decimal> SAL_MENS { get; set; }
        public Nullable<decimal> SAL_DIARIO { get; set; }
        public Nullable<decimal> SAL_DIA_INT { get; set; }
        public Nullable<decimal> SAL_DIA_SAR { get; set; }
        public Nullable<decimal> SAL_DIA_INFO { get; set; }
        public Nullable<decimal> SAL_INT_FINI { get; set; }
        public string SAL_MINIMO { get; set; }
        public string SIN_USO59 { get; set; }
        public string SIN_USO60 { get; set; }
        public Nullable<decimal> ADICION1_NUM { get; set; }
        public Nullable<decimal> ADICION2_NUM { get; set; }
        public string ADICION1_FECH { get; set; }
        public string ADICION2_FECH { get; set; }
        public string ADICION1_ALFA { get; set; }
        public string ADICION2_ALFA { get; set; }
        public string ADICION3_ALFA { get; set; }
        public string ADICION4_ALFA { get; set; }
        public Nullable<int> FOLIO_CONTRATO { get; set; }
        public string C_BAJA { get; set; }
        public string NOMP_EMP_NORMAL { get; set; }
        public string AP_PATER_NORMAL { get; set; }
        public string AP_MATER_NORMAL { get; set; }
        public string F_ALTA_CA { get; set; }
        public string F_BAJA_CA { get; set; }
        public string CBAJA_CA { get; set; }
        public Nullable<decimal> PORC_CA { get; set; }
        public Nullable<decimal> IMPORTE_CA { get; set; }
        public string F_VIGOR { get; set; }
        public string RETENCION_CA { get; set; }
    }
}
